/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8aa494fe-d5c1-4421-8a51-5d761bcd7daa",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_KNtmIfeRU",
    "aws_user_pools_web_client_id": "22tdthtgb3udkk5vt6hkg9210n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://l34y345gqrdynaji3fwcyjayja.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wow4bj3cmfhprbrwja5tv3onhe",
    "aws_user_files_s3_bucket": "amplifyappa89bca712429416b82de396a8785bc5f171321-vscode",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
